version: '3'
services:  
  api:
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - auth_db
    volumes: [.:/app]
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  auth_db:
    container_name: auth_db
    hostname: auth_db
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /data/volumes/auth-service/my_db:/var/lib/postgresql/data/